In [1]:
"""
price - target(listing price prediction)
In here I only use clean dataset .parquet 
mallorca_listings_clean.parquet
"""

'\nprice - target(listing price prediction)\nIn here I only use clean dataset .parquet \nmallorca_listings_clean.parquet\n'

# Import Libaries

In [2]:
import polars as pl
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import KFold, cross_validate

# Analyze basic stat of dataset

In [3]:
df = pl.read_parquet("/home/naviya-c/Desktop/airbnb_fixed/data/interim/mallorca_listings_clean.parquet")
pdf = df.to_pandas()

In [4]:
pdf.shape

(14817, 101)

In [5]:
pdf['neighborhood_overview'].isna().sum()

np.int64(14817)

"""
All 'neighborhood_overview' is null, 
Therefore drop that column
"""

# Feature Engineer

In [6]:
pdf_1 = pdf.loc[:, pdf.isnull().mean() <= 0.9]

In [7]:
numeric = pdf_1.select_dtypes(include=["number"])

corr = (
    numeric.corr(numeric_only=True)["price"]
    .drop("price")
    .sort_values(key=abs, ascending=False)
)

remove = corr[abs(corr) <= 0.3].index

pdf_2 = pdf_1.drop(remove, axis = 1)

#### Remove threshold < 0.3

In [8]:
pdf_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 14817 entries, 0 to 14816
Data columns (total 58 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   city_key                                      14817 non-null  str
 1   snapshot_date                                 14817 non-null  str
 2   listing_url                                   14817 non-null  str
 3   scrape_id                                     14817 non-null  str
 4   last_scraped                                  14817 non-null  datetime64[ms]
 5   source                                        14817 non-null  str
 6   name                                          14817 non-null  str
 7   description                                   14529 non-null  str
 8   picture_url                                   14817 non-null  str
 9   host_url                                      14817 non-null  str
 10  host_profile_id                               14817 non-null  str
 11  host_profile_url                              14815 non-null  str
 12  host_name                                     14817 non-null  str
 13  hosts_time_as_user_years                      14817 non-null  str
 14  hosts_time_as_user_months                     14817 non-null  str
 15  hosts_time_as_host_years                      14817 non-null  str
 16  hosts_time_as_host_months                     14817 non-null  str
 17  host_location                                 10902 non-null  str
 18  host_about                                    10422 non-null  str
 19  host_is_superhost                             14817 non-null  bool
 20  host_picture_url                              14817 non-null  str
 21  host_listings_count                           14817 non-null  int64
 22  host_has_profile_pic                          14817 non-null  str
 23  host_identity_verified                        14817 non-null  bool
 24  neighbourhood_cleansed                        14817 non-null  str
 25  property_type                                 14817 non-null  str
 26  room_type                                     14817 non-null  str
 27  accommodates                                  14817 non-null  int64
 28  bathrooms                                     13155 non-null  str
 29  bathrooms_text                                14812 non-null  str
 30  bedrooms                                      14320 non-null  float64
 31  beds                                          13726 non-null  float64
 32  amenities                                     14817 non-null  str
 33  price                                         11057 non-null  float64
 34  price_quote_checkin_date                      14367 non-null  str
 35  price_quote_checkout_date                     14367 non-null  str
 36  price_quote_total_price                       11057 non-null  float64
 37  price_quote_price_per_night                   11057 non-null  float64
 38  price_quote_raw                               14367 non-null  str
 39  maximum_minimum_nights                        14814 non-null  str
 40  has_availability                              14806 non-null  str
 41  calendar_last_scraped                         14817 non-null  str
 42  first_review                                  11609 non-null  datetime64[ms]
 43  last_review                                   11609 non-null  datetime64[ms]
 44  license                                       14754 non-null  str
 45  calculated_host_listings_count                14817 non-null  int64
 46  calculated_host_listings_count_entire_homes   14817 non-null  int64
 47  calculated_host_listings_count_private_rooms  14817 non-null  int64
 48  calculated_host_listings_count_shared_rooms   14817 non-null  int64
 49  host_is_superhost_missing                     14817 non-null  bool
 50  host_identity_verified_missing                14817 non-null  bool
 51  property_type_clean                           14817 non-null  str
 52  property_family                               14817 non-null  str
 53  neighbourhood_std                             14817 non-null  str
 54  bedrooms_imputed                              14817 non-null  bool
 55  bedrooms_filled                               14817 non-null  float64
 56  beds_imputed                                  14817 non-null  bool
 57  beds_filled                                   14817 non-null  float64
dtypes: bool(6), datetime64[ms](3), float64(7), int64(6), str(36)
memory usage: 46.7 MB

Removing these columns:
     city_key                                              
 1   snapshot_date                                            
 2   listing_url                                          
 3   scrape_id                                     1         
 4   last_scraped                                 
 5   source                                                 
 6   name                                                    
 7   description                                            
 8   picture_url                                            
 9   host_url                                             
 10  host_profile_id                                        
 12  host_name

In [9]:
removing_col = pdf_2.columns[:13]

In [10]:
pdf_3 = pdf_2.drop(removing_col, axis = 1)

In [11]:
pdf_3.info()

<class 'pandas.DataFrame'>
RangeIndex: 14817 entries, 0 to 14816
Data columns (total 45 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   hosts_time_as_user_years                      14817 non-null  str
 1   hosts_time_as_user_months                     14817 non-null  str
 2   hosts_time_as_host_years                      14817 non-null  str
 3   hosts_time_as_host_months                     14817 non-null  str
 4   host_location                                 10902 non-null  str
 5   host_about                                    10422 non-null  str
 6   host_is_superhost                             14817 non-null  bool
 7   host_picture_url                              14817 non-null  str
 8   host_listings_count                           14817 non-null  int64
 9   host_has_profile_pic                          14817 non-null  str
 10  host_identity_verified                        14817 non-null  bool
 11  neighbourhood_cleansed                        14817 non-null  str
 12  property_type                                 14817 non-null  str
 13  room_type                                     14817 non-null  str
 14  accommodates                                  14817 non-null  int64
 15  bathrooms                                     13155 non-null  str
 16  bathrooms_text                                14812 non-null  str
 17  bedrooms                                      14320 non-null  float64
 18  beds                                          13726 non-null  float64
 19  amenities                                     14817 non-null  str
 20  price                                         11057 non-null  float64
 21  price_quote_checkin_date                      14367 non-null  str
 22  price_quote_checkout_date                     14367 non-null  str
 23  price_quote_total_price                       11057 non-null  float64
 24  price_quote_price_per_night                   11057 non-null  float64
 25  price_quote_raw                               14367 non-null  str
 26  maximum_minimum_nights                        14814 non-null  str
 27  has_availability                              14806 non-null  str
 28  calendar_last_scraped                         14817 non-null  str
 29  first_review                                  11609 non-null  datetime64[ms]
 30  last_review                                   11609 non-null  datetime64[ms]
 31  license                                       14754 non-null  str
 32  calculated_host_listings_count                14817 non-null  int64
 33  calculated_host_listings_count_entire_homes   14817 non-null  int64
 34  calculated_host_listings_count_private_rooms  14817 non-null  int64
 35  calculated_host_listings_count_shared_rooms   14817 non-null  int64
 36  host_is_superhost_missing                     14817 non-null  bool
 37  host_identity_verified_missing                14817 non-null  bool
 38  property_type_clean                           14817 non-null  str
 39  property_family                               14817 non-null  str
 40  neighbourhood_std                             14817 non-null  str
 41  bedrooms_imputed                              14817 non-null  bool
 42  bedrooms_filled                               14817 non-null  float64
 43  beds_imputed                                  14817 non-null  bool
 44  beds_filled                                   14817 non-null  float64
dtypes: bool(6), datetime64[ms](2), float64(7), int64(6), str(24)
memory usage: 35.3 MB

In [12]:
remove_col = ['hosts_time_as_user_years', 'hosts_time_as_user_months', 'hosts_time_as_host_months','host_is_superhost_missing', 'bathrooms_text', 'has_availability', 'host_location', 'host_has_profile_pic', 'maximum_minimum_nights', 'calendar_last_scraped','beds_filled','bedrooms_filled', 'price_quote_checkin_date', 'price_quote_checkout_date', 'first_review', 'last_review', 'price_quote_raw', 'host_picture_url', 'host_about', 'price_quote_total_price', 'price_quote_price_per_night']

In [13]:
pdf_4 = pdf_3.drop(remove_col, axis=1)

In [14]:
pdf_4.shape

(14817, 24)

In [15]:
pdf_4.info()

<class 'pandas.DataFrame'>
RangeIndex: 14817 entries, 0 to 14816
Data columns (total 24 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   hosts_time_as_host_years                      14817 non-null  str
 1   host_is_superhost                             14817 non-null  bool
 2   host_listings_count                           14817 non-null  int64
 3   host_identity_verified                        14817 non-null  bool
 4   neighbourhood_cleansed                        14817 non-null  str
 5   property_type                                 14817 non-null  str
 6   room_type                                     14817 non-null  str
 7   accommodates                                  14817 non-null  int64
 8   bathrooms                                     13155 non-null  str
 9   bedrooms                                      14320 non-null  float64
 10  beds                                          13726 non-null  float64
 11  amenities                                     14817 non-null  str
 12  price                                         11057 non-null  float64
 13  license                                       14754 non-null  str
 14  calculated_host_listings_count                14817 non-null  int64
 15  calculated_host_listings_count_entire_homes   14817 non-null  int64
 16  calculated_host_listings_count_private_rooms  14817 non-null  int64
 17  calculated_host_listings_count_shared_rooms   14817 non-null  int64
 18  host_identity_verified_missing                14817 non-null  bool
 19  property_type_clean                           14817 non-null  str
 20  property_family                               14817 non-null  str
 21  neighbourhood_std                             14817 non-null  str
 22  bedrooms_imputed                              14817 non-null  bool
 23  beds_imputed                                  14817 non-null  bool
dtypes: bool(5), float64(3), int64(6), str(10)
memory usage: 14.5 MB

In [16]:
pdf_5 = pdf_4.dropna(subset=['price'])

In [17]:
pdf_5.shape

(11057, 24)

In [18]:
pdf_5.info()

<class 'pandas.DataFrame'>
Index: 11057 entries, 1 to 14805
Data columns (total 24 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   hosts_time_as_host_years                      11057 non-null  str
 1   host_is_superhost                             11057 non-null  bool
 2   host_listings_count                           11057 non-null  int64
 3   host_identity_verified                        11057 non-null  bool
 4   neighbourhood_cleansed                        11057 non-null  str
 5   property_type                                 11057 non-null  str
 6   room_type                                     11057 non-null  str
 7   accommodates                                  11057 non-null  int64
 8   bathrooms                                     10145 non-null  str
 9   bedrooms                                      10713 non-null  float64
 10  beds                                          10700 non-null  float64
 11  amenities                                     11057 non-null  str
 12  price                                         11057 non-null  float64
 13  license                                       11031 non-null  str
 14  calculated_host_listings_count                11057 non-null  int64
 15  calculated_host_listings_count_entire_homes   11057 non-null  int64
 16  calculated_host_listings_count_private_rooms  11057 non-null  int64
 17  calculated_host_listings_count_shared_rooms   11057 non-null  int64
 18  host_identity_verified_missing                11057 non-null  bool
 19  property_type_clean                           11057 non-null  str
 20  property_family                               11057 non-null  str
 21  neighbourhood_std                             11057 non-null  str
 22  bedrooms_imputed                              11057 non-null  bool
 23  beds_imputed                                  11057 non-null  bool
dtypes: bool(5), float64(3), int64(6), str(10)
memory usage: 11.3 MB

In [19]:
pdf_5.head()

,hosts_time_as_host_years,host_is_superhost,host_listings_count,host_identity_verified,neighbourhood_cleansed,property_type,room_type,accommodates,bathrooms,bedrooms,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,host_identity_verified_missing,property_type_clean,property_family,neighbourhood_std,bedrooms_imputed,beds_imputed
1,1,False,1,True,Búger,Entire chalet,Entire home/apt,6,2.5,3.0,...,1,1,0,0,False,Entire Chalet,Entire place,Búger,False,False
2,2,False,219,True,Pollença,Entire villa,Entire home/apt,2,1.0,1.0,...,40,40,0,0,False,Entire Villa,Entire place,Pollença,False,False
3,11,True,24,True,Sant Llorenç des Cardassar,Entire home,Entire home/apt,8,3.0,4.0,...,24,24,0,0,False,Entire Home,Entire place,Sant Llorenç des Cardassar,False,False
4,11,False,57,True,Pollença,Entire home,Entire home/apt,5,NaN,3.0,...,57,57,0,0,False,Entire Home,Entire place,Pollença,False,False
5,10,False,160,True,Santanyí,Entire villa,Entire home/apt,8,4.0,4.0,...,159,159,0,0,False,Entire Villa,Entire place,Santanyí,False,False

In [20]:
pdf_5['bathrooms']

1        2.5
2        1.0
3        3.0
4        NaN
5        4.0
        ...
14769    NaN
14779    NaN
14780    NaN
14783    NaN
14805    NaN
Name: bathrooms, Length: 11057, dtype: str

In [21]:
pdf_5["bathrooms"] = pd.to_numeric(pdf_5["bathrooms"], errors="coerce")
pdf_5["hosts_time_as_host_years"] = pd.to_numeric(pdf_5["hosts_time_as_host_years"], errors="coerce")

In [22]:
pdf_5.info()

<class 'pandas.DataFrame'>
Index: 11057 entries, 1 to 14805
Data columns (total 24 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   hosts_time_as_host_years                      11057 non-null  int64
 1   host_is_superhost                             11057 non-null  bool
 2   host_listings_count                           11057 non-null  int64
 3   host_identity_verified                        11057 non-null  bool
 4   neighbourhood_cleansed                        11057 non-null  str
 5   property_type                                 11057 non-null  str
 6   room_type                                     11057 non-null  str
 7   accommodates                                  11057 non-null  int64
 8   bathrooms                                     10145 non-null  float64
 9   bedrooms                                      10713 non-null  float64
 10  beds                                          10700 non-null  float64
 11  amenities                                     11057 non-null  str
 12  price                                         11057 non-null  float64
 13  license                                       11031 non-null  str
 14  calculated_host_listings_count                11057 non-null  int64
 15  calculated_host_listings_count_entire_homes   11057 non-null  int64
 16  calculated_host_listings_count_private_rooms  11057 non-null  int64
 17  calculated_host_listings_count_shared_rooms   11057 non-null  int64
 18  host_identity_verified_missing                11057 non-null  bool
 19  property_type_clean                           11057 non-null  str
 20  property_family                               11057 non-null  str
 21  neighbourhood_std                             11057 non-null  str
 22  bedrooms_imputed                              11057 non-null  bool
 23  beds_imputed                                  11057 non-null  bool
dtypes: bool(5), float64(4), int64(7), str(8)
memory usage: 11.3 MB

In [23]:
pdf_5['license'].unique()

<ArrowStringArray>
[    'Spain - National registration number<br />ESFCTU000007022000236176000000000000000000000ETV/4112<br /><br />Mallorca - Regional registration number<br />ETV/411',
     'Mallorca - Regional registration number<br />ETV/654<br /><br />Spain - National registration number<br />ESFCTU000007030000313469000000000000000000000ETV/6543',
    'Spain - National registration number<br />ESFCTU00000702300017664600000000000000000000ETV/35624<br /><br />Mallorca - Regional registration number<br />ETV/3562',
    'Spain - National registration number<br />ESFCTU00000703000015775900000000000000000000ETV/16960<br /><br />Mallorca - Regional registration number<br />ETV/1696',
    'Spain - National registration number<br />ESFCTU00000700800074055400000000000000000000ETV/80677<br /><br />Mallorca - Regional registration number<br />ETV/8067',
     'Spain - National registration number<br />ESFCTU000007030000046886000000000000000000000ETV/1056<br /><br />Mallorca - Regional registration number<br />ETV/105',
     'Spain - National registration number<br />ESFCTU000007030000033053000000000000000000000ETV/1171<br /><br />Mallorca - Regional registration number<br />ETV/117',
    'Spain - National registration number<br />ESFCTU00000702300011648200000000000000000000ETV/36340<br /><br />Mallorca - Regional registration number<br />ETV/3634',
    'Spain - National registration number<br />ESFCTU00000703800125347000000000000000000000ETV/52308<br /><br />Mallorca - Regional registration number<br />ETV/5230',
     'Spain - National registration number<br />ESFCTU000007030000310833000000000000000000000ETV/3063<br /><br />Mallorca - Regional registration number<br />ETV/306',
 ...
   'Spain - National registration number<br />ESFCTU0000070080001532170000000000000000000ETV-134138<br /><br />Mallorca - Regional registration number<br />ETV-13413',
 'Spain - National registration number<br />ESFCTU00000702500023217900000000000000000ETV760157928<br /><br />Mallorca - Regional registration number<br />ETV60/15792',
   'Mallorca - Regional registration number<br />ETV/20002<br /><br />Spain - National registration number<br />ESFCTU00000702800004244100000000000000000000ETV/20002',
    'Spain - National registration number<br />ESFCTU00000708000682069000000000000000000000ETV/17525<br /><br />Mallorca - Regional registration number<br />ETV/1752',
   'Mallorca - Regional registration number<br />ETV/11264<br /><br />Spain - National registration number<br />ESFCTU0000070110003568470000000000000000000ETV/112646',
    'Spain - National registration number<br />ESFCTU00000702200050303200000000000000000000ETV/60314<br /><br />Mallorca - Regional registration number<br />ETV/6031',
     'Spain - National registration number<br />ESFCTU000007030000408899000000000000000000000ETV/1113<br /><br />Mallorca - Regional registration number<br />ETV/111',
                                                                                                                'Mallorca - Regional registration number<br />ETV/919',
    'Mallorca - Regional registration number<br />ETV/5981<br /><br />Spain - National registration number<br />ESFCTU00000700800073789900000000000000000000ETV/59817',
                                                                                                               'Mallorca - Regional registration number<br />ETV 9913']
Length: 9347, dtype: str

In [24]:
pdf_5["license"] = (
    pdf_5["license"]
      .fillna("")
      .str.contains(r"\b(?:ESFC|ETV)\b", case=False)
)

In [25]:
pdf_5.info()

<class 'pandas.DataFrame'>
Index: 11057 entries, 1 to 14805
Data columns (total 24 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   hosts_time_as_host_years                      11057 non-null  int64
 1   host_is_superhost                             11057 non-null  bool
 2   host_listings_count                           11057 non-null  int64
 3   host_identity_verified                        11057 non-null  bool
 4   neighbourhood_cleansed                        11057 non-null  str
 5   property_type                                 11057 non-null  str
 6   room_type                                     11057 non-null  str
 7   accommodates                                  11057 non-null  int64
 8   bathrooms                                     10145 non-null  float64
 9   bedrooms                                      10713 non-null  float64
 10  beds                                          10700 non-null  float64
 11  amenities                                     11057 non-null  str
 12  price                                         11057 non-null  float64
 13  license                                       11057 non-null  bool
 14  calculated_host_listings_count                11057 non-null  int64
 15  calculated_host_listings_count_entire_homes   11057 non-null  int64
 16  calculated_host_listings_count_private_rooms  11057 non-null  int64
 17  calculated_host_listings_count_shared_rooms   11057 non-null  int64
 18  host_identity_verified_missing                11057 non-null  bool
 19  property_type_clean                           11057 non-null  str
 20  property_family                               11057 non-null  str
 21  neighbourhood_std                             11057 non-null  str
 22  bedrooms_imputed                              11057 non-null  bool
 23  beds_imputed                                  11057 non-null  bool
dtypes: bool(6), float64(4), int64(7), str(7)
memory usage: 9.6 MB

In [26]:
pdf_5["bathrooms"] = pdf_5["bathrooms"].fillna(pdf_5["bathrooms"].median())

In [27]:
# Bedrooms
pdf_5["bedrooms_imputed"] = pdf_5["bedrooms"].isna()
pdf_5["bedrooms"] = pdf_5["bedrooms"].fillna(pdf_5["bedrooms"].median())

# Beds
pdf_5["beds_imputed"] = pdf_5["beds"].isna()
pdf_5["beds"] = pdf_5["beds"].fillna(pdf_5["beds"].median())

# Bathrooms
pdf_5["bathrooms_imputed"] = pdf_5["bathrooms"].isna()
pdf_5["bathrooms"] = pdf_5["bathrooms"].fillna(pdf_5["bathrooms"].median())

In [28]:
pdf_5.info()

<class 'pandas.DataFrame'>
Index: 11057 entries, 1 to 14805
Data columns (total 25 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   hosts_time_as_host_years                      11057 non-null  int64
 1   host_is_superhost                             11057 non-null  bool
 2   host_listings_count                           11057 non-null  int64
 3   host_identity_verified                        11057 non-null  bool
 4   neighbourhood_cleansed                        11057 non-null  str
 5   property_type                                 11057 non-null  str
 6   room_type                                     11057 non-null  str
 7   accommodates                                  11057 non-null  int64
 8   bathrooms                                     11057 non-null  float64
 9   bedrooms                                      11057 non-null  float64
 10  beds                                          11057 non-null  float64
 11  amenities                                     11057 non-null  str
 12  price                                         11057 non-null  float64
 13  license                                       11057 non-null  bool
 14  calculated_host_listings_count                11057 non-null  int64
 15  calculated_host_listings_count_entire_homes   11057 non-null  int64
 16  calculated_host_listings_count_private_rooms  11057 non-null  int64
 17  calculated_host_listings_count_shared_rooms   11057 non-null  int64
 18  host_identity_verified_missing                11057 non-null  bool
 19  property_type_clean                           11057 non-null  str
 20  property_family                               11057 non-null  str
 21  neighbourhood_std                             11057 non-null  str
 22  bedrooms_imputed                              11057 non-null  bool
 23  beds_imputed                                  11057 non-null  bool
 24  bathrooms_imputed                             11057 non-null  bool
dtypes: bool(7), float64(4), int64(7), str(7)
memory usage: 9.6 MB

In [29]:
target = pdf_5['price']
features = pdf_5.drop('price', axis = 1)

In [30]:
features['neighbourhood_cleansed'].unique().shape

(53,)

In [31]:
features = pd.get_dummies(
    features,
    columns=[
        "room_type",
        "property_type",
        "neighbourhood_cleansed",
        "property_type_clean",
        "property_family",
        "neighbourhood_std",
    ],
    drop_first=True,
    dtype=bool,
)

In [32]:
features.shape

(11057, 233)

In [33]:
important_amenities = [
    "Wifi",
    "Kitchen",
    "Air conditioning",
    "Heating",
    "TV",
    "Washer",
    "Dryer",
    "Dishwasher",
    "Refrigerator",
    "Microwave",
    "Oven",
    "Coffee maker",
    "Free parking on premises",
    "Pool",
    "Hot tub",
    "Gym",
    "BBQ grill",
    "Outdoor dining area",
    "Outdoor furniture",
    "Patio or balcony",
    "Garden view",
    "Beach access",
    "Waterfront",
    "Dedicated workspace",
    "Indoor fireplace",
    "Elevator",
    "Smoke alarm",
    "Carbon monoxide alarm",
    "First aid kit",
    "Fire extinguisher",
    "Hair dryer",
    "Iron",
    "Hot water",
    "Crib",
    "High chair",
    "Pets allowed",
    "Self check-in",
    "Lockbox",
    "Private entrance",
    "EV charger"
]

In [34]:
import re

for amenity in important_amenities:
    col = "has_" + re.sub(r"[^a-z0-9]+", "_", amenity.lower()).strip("_")

    features[col] = features["amenities"].apply(
        lambda x: any(amenity.lower() in item.lower() for item in x)
    )

features = features.drop(columns=["amenities"])

In [35]:
features.shape

(11057, 272)

# Train Model

In [36]:
target = np.log1p(target)

In [37]:
X_train, X_test, y_train, y_test = train_test_split(
    features,
    target,
    test_size=0.2,
    random_state=42,
)

In [38]:
cv = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42,
)

In [39]:
scoring = {
    "MAE": "neg_mean_absolute_error",
    "RMSE": "neg_root_mean_squared_error",
    "MAPE": "neg_mean_absolute_percentage_error",
}

In [40]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(
        n_estimators=300,
        random_state=42,
        n_jobs=-1,
    ),
    "XGBoost": XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        random_state=42,
    ),
}

In [41]:
import pandas as pd

results = []

for name, model in models.items():

    scores = cross_validate(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring=scoring,
        n_jobs=-1,
    )

    results.append({
        "Model": name,
        "MAE": -scores["test_MAE"].mean(),
        "RMSE": -scores["test_RMSE"].mean(),
        "MAPE": -scores["test_MAPE"].mean(),
    })

results = pd.DataFrame(results)
results.sort_values("RMSE")

               Model       MAE      RMSE      MAPE
2            XGBoost  0.368263  0.489352  0.061723
1      Random Forest  0.372167  0.501647  0.062135
0  Linear Regression  0.415317  0.549845  0.069638

In [43]:
best_model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42,
)

best_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)