In [1]:
import pandas as pd

# Detailed Listing Explore(Detailed/listing.csv)

In [2]:
detailedListing_df = pd.read_csv("Detailed/listings.csv")
detailedReview_df = pd.read_csv("Detailed/reviews.csv")
detailedCalander_df = pd.read_csv("Detailed/calendar.csv")
neighbourhood_df = pd.read_csv("neighbourhoods.csv")

In [3]:
detailedListing_df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,10803,https://www.airbnb.com/rooms/10803,20260616211523,2026-06-17,city scrape,"Room in Deco Apartment, Brunswick East",A large air conditioned room with firm queen s...,NaN,https://a0.muscache.com/pictures/e5f30dd1-ac57...,38901,...,4.73,4.70,4.66,NaN,NaN,1,0,1,0,1.31
1,12936,https://www.airbnb.com/rooms/12936,20260616211523,2026-06-28,previous scrape,St Kilda 1BR+BEACHSIDE+BALCONY+WIFI+AC,RIGHT IN THE HEART OF ST KILDA! It doesn't get...,NaN,https://a0.muscache.com/pictures/59701/2e8cdaf...,50121,...,4.83,4.78,4.66,NaN,NaN,10,10,0,0,0.22
2,41836,https://www.airbnb.com/rooms/41836,20260616211523,2026-06-28,previous scrape,CLOSE TO CITY & MELBOURNE AIRPORT,Easy to travel from and to the Airport; quiet ...,NaN,https://a0.muscache.com/pictures/569696dd-1ad0...,182833,...,4.83,4.39,4.69,NaN,NaN,2,0,2,0,0.83
3,43429,https://www.airbnb.com/rooms/43429,20260616211523,2026-06-17,city scrape,Tranquil Javanese Studio and Pond!,"No service/Cleaning Fees, EV Charger, Study th...",NaN,https://a0.muscache.com/pictures/airflow/Hosti...,189684,...,4.94,4.79,4.86,NaN,NaN,2,2,0,0,1.48
4,44699,https://www.airbnb.com/rooms/44699,20260616211523,2026-06-17,city scrape,"15 yearsHosting (4.8), 8 CITY TRAMS, GymPoolTe...",Unwavering service — just ask and we do our be...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,189245,...,4.97,4.84,4.71,NaN,NaN,1,0,1,0,0.35

In [4]:
x = detailedListing_df['price'].replace("$", "")

In [5]:
x

0         $60.74
1            NaN
2            NaN
3        $165.00
4        $215.00
          ...
25723    $100.00
25724    $197.50
25725    $364.40
25726        NaN
25727    $127.48
Name: price, Length: 25728, dtype: str

In [6]:
detailedListing_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25728 entries, 0 to 25727
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            25728 non-null  int64
 1   listing_url                                   25728 non-null  str
 2   scrape_id                                     25728 non-null  int64
 3   last_scraped                                  25728 non-null  str
 4   source                                        25728 non-null  str
 5   name                                          25728 non-null  str
 6   description                                   25276 non-null  str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   25728 non-null  str
 9   host_id                                       25728 non-null  int64
 10  host_url                                      25728 non-null  str
 11  host_profile_id                               25728 non-null  int64
 12  host_profile_url                              25728 non-null  str
 13  host_name                                     25728 non-null  str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      25728 non-null  int64
 16  hosts_time_as_user_months                     25728 non-null  int64
 17  hosts_time_as_host_years                      25728 non-null  int64
 18  hosts_time_as_host_months                     25728 non-null  int64
 19  host_location                                 18772 non-null  str
 20  host_about                                    14362 non-null  str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             25728 non-null  str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              25728 non-null  str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           25728 non-null  int64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          25728 non-null  str
 32  host_identity_verified                        25728 non-null  str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        25728 non-null  str
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      25728 non-null  float64
 37  longitude                                     25728 non-null  float64
 38  property_type                                 25728 non-null  str
 39  room_type                                     25728 non-null  str
 40  accommodates                                  25728 non-null  int64
 41  bathrooms                                     17570 non-null  float64
 42  bathrooms_text                                25702 non-null  str
 43  bedrooms                                      21049 non-null  float64
 44  beds                                          18669 non-null  float64
 45  amenities                                     25728 non-null  str
 46  price                                         19175 non-null  str
 47  price_quote_checkin_date                      19457 non-null  str
 48  price_quote_checkout_date                     19457 non-null  str
 49  price_quote_total_price                       19175 non-null  float64
 50  price_quote_price_per_night                   19175 non-null  float64
 51  price_quote_raw                               19457 non-null  str
 52  minimum_nights                                25719 non-null  float64
 53  maximum_nights                                25719 non-null  float64
 54  minimum_minimum_nights                        25719 non-null  float64
 55  maximum_minimum_nights                        25719 non-null  float64
 56  minimum_maximum_nights                        25719 non-null  float64
 57  maximum_maximum_nights                        25719 non-null  float64
 58  minimum_nights_avg_ntm                        25728 non-null  float64
 59  maximum_nights_avg_ntm                        25728 non-null  float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              25580 non-null  str
 62  availability_30                               25728 non-null  int64
 63  availability_60                               25728 non-null  int64
 64  availability_90                               25728 non-null  int64
 65  availability_365                              25728 non-null  int64
 66  calendar_last_scraped                         25728 non-null  str
 67  number_of_reviews                             25728 non-null  int64
 68  number_of_reviews_ltm                         25728 non-null  int64
 69  number_of_reviews_l30d                        25728 non-null  int64
 70  availability_eoy                              25728 non-null  int64
 71  number_of_reviews_ly                          25728 non-null  int64
 72  estimated_occupancy_l365d                     25728 non-null  int64
 73  estimated_revenue_l365d                       19175 non-null  float64
 74  first_review                                  21251 non-null  str
 75  last_review                                   21251 non-null  str
 76  review_scores_rating                          21251 non-null  float64
 77  review_scores_accuracy                        21247 non-null  float64
 78  review_scores_cleanliness                     21250 non-null  float64
 79  review_scores_checkin                         21244 non-null  float64
 80  review_scores_communication                   21247 non-null  float64
 81  review_scores_location                        21244 non-null  float64
 82  review_scores_value                           21244 non-null  float64
 83  license                                       0 non-null      float64
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                25728 non-null  int64
 86  calculated_host_listings_count_entire_homes   25728 non-null  int64
 87  calculated_host_listings_count_private_rooms  25728 non-null  int64
 88  calculated_host_listings_count_shared_rooms   25728 non-null  int64
 89  reviews_per_month                             21251 non-null  float64
dtypes: float64(38), int64(24), str(28)
memory usage: 17.7 MB

In [7]:
detailedListing_schema_df = detailedListing_df.dtypes.reset_index()

detailedListing_schema_df.columns = ["Column Name", "Data Type"]

In [8]:
detailedListing_schema_df.head()

    Column Name Data Type
0            id     int64
1   listing_url       str
2     scrape_id     int64
3  last_scraped       str
4        source       str

In [9]:
def extract(df) -> pd.DataFrame:

    Detailed_Data = []
    
    for col in df.columns:
        dtype = df[col].dtype
    
        sample_value = df[col].dropna().unique()[:1].tolist()
        is_valid = pd.api.types.is_numeric_dtype(dtype) or pd.api.types.is_datetime64_any_dtype(dtype)
    
        Detailed_Data.append({
            'Column Name': col,
            'Data Type': dtype,
            'Min Value': df[col].min() if is_valid else 'N/A',
            'Max Value': df[col].max() if is_valid else 'N/A',
            'Sample Values': sample_value
        })
    
    return pd.DataFrame(Detailed_Data)

In [10]:
detailedListing_subset_df = extract(detailedListing_df)
detailedReview_subset_df = extract(detailedReview_df)
detailedCalander_subset_df = extract(detailedCalander_df)
#neighbourhood_df = extract(neighbourhood_df)

In [11]:
with pd.ExcelWriter("airbnb_melbourne_schema_documentation.xlsx", engine = "openpyxl") as writer:
    detailedListing_subset_df.to_excel(writer, sheet_name = "Listing Schema", index = False)
    detailedReview_subset_df.to_excel(writer, sheet_name = "Review Schema", index = False)
    detailedCalander_subset_df.to_excel(writer, sheet_name = "Calander Schema", index = False)

## Finding the Relationships & PK and Fks

In [12]:
dataframes = {
    'listing': detailedListing_df,
    'review': detailedReview_df,
    'calander': detailedCalander_df,
}

In [13]:
import pandas as pd

def profile_pk_fk(dfs: dict[str, pd.DataFrame]):
    summary = {}
    
    # 1. Identify Primary Key Candidates
    for name, df in dfs.items():
        total_rows = len(df)
        pks = [col for col in df.columns if df[col].nunique() == total_rows and total_rows > 0]
        summary[name] = {"pk_candidates": pks, "fk_candidates": []}
    
    # 2. Identify Foreign Key Candidates
    for table_a, df_a in dfs.items():
        for table_b, df_b in dfs.items():
            if table_a == table_b:
                continue
                
            # Check if columns in Table B match a confirmed PK candidate in Table A
            for pk in summary[table_a]["pk_candidates"]:
                for col_b in df_b.columns:
                    # Match by name convention and data subset
                    if pk in col_b or col_b in pk:
                        set_a = set(df_a[pk].dropna())
                        set_b = set(df_b[col_b].dropna())
                        
                        # If B is a subset of A, it's a Foreign Key
                        if set_b.issubset(set_a) and len(set_b) > 0:
                            summary[table_b]["fk_candidates"].append({
                                "column": col_b,
                                "references_table": table_a,
                                "references_column": pk
                            })
                            
    return summary

In [14]:
profile_pk_fk(dataframes)

{'listing': {'pk_candidates': ['id', 'listing_url'], 'fk_candidates': []},
 'review': {'pk_candidates': ['id'],
  'fk_candidates': [{'column': 'listing_id',
    'references_table': 'listing',
    'references_column': 'id'}]},
 'calander': {'pk_candidates': [],
  'fk_candidates': [{'column': 'listing_id',
    'references_table': 'listing',
    'references_column': 'id'}]}}

In [15]:
detailedCalander_df.head()

   listing_id        date available  minimum_nights  maximum_nights
0       10803  2026-06-17         f              12              28
1       10803  2026-06-18         f              12              28
2       10803  2026-06-19         t              12              28
3       10803  2026-06-20         t              12              28
4       10803  2026-06-21         t              12              28

In [16]:
detailedCalander_df['listing_id'].is_unique

False

In [17]:
detailedCalander_df['date'].is_unique

False

In [18]:
composite_cols = ['listing_id', 'date']
is_composite_unique = not detailedCalander_df.duplicated(subset=composite_cols).any()

In [19]:
is_composite_unique

True

Considering the whole output and examine the dataframe final conlcusion:
    - Listing, 'id' is PRIMARY KEY.
    - REVIEW, 'id' is PRIMARY KEY & 'listing_id' is FOREIGN KEY (listing dataframe -> id)
    - CALANDER, 'listing_id + date' is COMPOSITE PRIMARY KEY & 'listing_id' is FORIEGN KEY (listing dataframe -> id)

In [20]:
detailedListing_df.dtypes.value_counts()

float64    38
str        28
int64      24
Name: count, dtype: int64

# Pipeline cleaned dataset examin

In [21]:
mallorca_raw = pd.read_csv("/home/naviya-c/Desktop/dataProject/stage_3/data/01_raw/mallorca/2026-06-23/listing.csv")

In [22]:
mallorca_cleaned = pd.read_csv("/home/naviya-c/Desktop/dataProject/stage_3/data/02_clean/mallorca/2026-06-23/listing_clean.csv")

In [23]:
mallorca_cleaned.head(4)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,1594759156338136230,https://www.airbnb.com/rooms/1594759156338136230,20260623040707,2026-06-23,city scrape,S'Hortet Gran,Arrive and feel at home.,0.0,https://a0.muscache.com/pictures/hosting/Hosti...,141515273,...,0.0,0.00,0.00,Mallorca - Regional registration number<br />E...,0.0,48,48,0,0,0.00
1,1273823517224415510,https://www.airbnb.com/rooms/1273823517224415510,20260623040707,2026-06-23,city scrape,Son Pere Genet,ETV 411 Recharge your batteries in this wonder...,0.0,https://a0.muscache.com/pictures/miso/Hosting-...,651077862,...,5.0,4.86,4.86,Spain - National registration number<br />ESFC...,0.0,1,1,0,0,0.47
2,1151380048474115597,https://www.airbnb.com/rooms/1151380048474115597,20260623040707,2026-06-23,city scrape,Ca Na Reieta by Vintage Travel,Ground Floor: Open plan living/dining room (TV...,0.0,https://a0.muscache.com/pictures/prohost-api/H...,565714005,...,0.0,0.00,0.00,Mallorca - Regional registration number<br />E...,0.0,40,40,0,0,0.00
3,1430444173039950930,https://www.airbnb.com/rooms/1430444173039950930,20260623040707,2026-06-23,city scrape,Villa Sofía,Vacation villa for 8 people with fenced pool a...,0.0,https://a0.muscache.com/pictures/miso/Hosting-...,29095214,...,0.0,0.00,0.00,Spain - National registration number<br />ESFC...,0.0,24,24,0,0,0.00

In [24]:
mallorca_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 14817 entries, 0 to 14816
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            14817 non-null  int64
 1   listing_url                                   14817 non-null  str
 2   scrape_id                                     14817 non-null  int64
 3   last_scraped                                  14817 non-null  str
 4   source                                        14817 non-null  str
 5   name                                          14817 non-null  str
 6   description                                   14529 non-null  str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   14817 non-null  str
 9   host_id                                       14817 non-null  int64
 10  host_url                                      14817 non-null  str
 11  host_profile_id                               14817 non-null  int64
 12  host_profile_url                              14815 non-null  str
 13  host_name                                     14817 non-null  str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      14817 non-null  int64
 16  hosts_time_as_user_months                     14817 non-null  int64
 17  hosts_time_as_host_years                      14817 non-null  int64
 18  hosts_time_as_host_months                     14817 non-null  int64
 19  host_location                                 10902 non-null  str
 20  host_about                                    10422 non-null  str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             14817 non-null  str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              14817 non-null  str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           14817 non-null  int64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          14817 non-null  str
 32  host_identity_verified                        14817 non-null  str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        14817 non-null  str
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      14817 non-null  float64
 37  longitude                                     14817 non-null  float64
 38  property_type                                 14817 non-null  str
 39  room_type                                     14817 non-null  str
 40  accommodates                                  14817 non-null  int64
 41  bathrooms                                     13155 non-null  float64
 42  bathrooms_text                                14812 non-null  str
 43  bedrooms                                      14320 non-null  float64
 44  beds                                          13726 non-null  float64
 45  amenities                                     14817 non-null  str
 46  price                                         11057 non-null  str
 47  price_quote_checkin_date                      14367 non-null  str
 48  price_quote_checkout_date                     14367 non-null  str
 49  price_quote_total_price                       11057 non-null  float64
 50  price_quote_price_per_night                   11057 non-null  float64
 51  price_quote_raw                               14367 non-null  str
 52  minimum_nights                                14814 non-null  float64
 53  maximum_nights                                14814 non-null  float64
 54  minimum_minimum_nights                        14814 non-null  float64
 55  maximum_minimum_nights                        14814 non-null  float64
 56  minimum_maximum_nights                        14814 non-null  float64
 57  maximum_maximum_nights                        14814 non-null  float64
 58  minimum_nights_avg_ntm                        14817 non-null  float64
 59  maximum_nights_avg_ntm                        14817 non-null  float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              14806 non-null  str
 62  availability_30                               14817 non-null  int64
 63  availability_60                               14817 non-null  int64
 64  availability_90                               14817 non-null  int64
 65  availability_365                              14817 non-null  int64
 66  calendar_last_scraped                         14817 non-null  str
 67  number_of_reviews                             14817 non-null  int64
 68  number_of_reviews_ltm                         14817 non-null  int64
 69  number_of_reviews_l30d                        14817 non-null  int64
 70  availability_eoy                              14817 non-null  int64
 71  number_of_reviews_ly                          14817 non-null  int64
 72  estimated_occupancy_l365d                     14817 non-null  int64
 73  estimated_revenue_l365d                       11057 non-null  float64
 74  first_review                                  11609 non-null  str
 75  last_review                                   11609 non-null  str
 76  review_scores_rating                          11609 non-null  float64
 77  review_scores_accuracy                        11609 non-null  float64
 78  review_scores_cleanliness                     11609 non-null  float64
 79  review_scores_checkin                         11609 non-null  float64
 80  review_scores_communication                   11609 non-null  float64
 81  review_scores_location                        11609 non-null  float64
 82  review_scores_value                           11609 non-null  float64
 83  license                                       14754 non-null  str
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                14817 non-null  int64
 86  calculated_host_listings_count_entire_homes   14817 non-null  int64
 87  calculated_host_listings_count_private_rooms  14817 non-null  int64
 88  calculated_host_listings_count_shared_rooms   14817 non-null  int64
 89  reviews_per_month                             11609 non-null  float64
dtypes: float64(37), int64(24), str(29)
memory usage: 10.2 MB

In [25]:
mallorca_cleaned['price'].head()

0      0.00
1    319.60
2    201.43
3    330.71
4    554.50
Name: price, dtype: float64

In [26]:
mallorca_raw['price'].head()

0        NaN
1    $319.60
2    $201.43
3    $330.71
4    $554.50
Name: price, dtype: str

In [71]:
mallorca_raw['last_scraped'].head()

0    2026-06-23
1    2026-06-23
2    2026-06-23
3    2026-06-23
4    2026-06-23
Name: last_scraped, dtype: str

In [57]:
mallorca_enrich = pd.read_csv("/home/naviya-c/Desktop/dataProject/stage_3/data/03_enriched/mallorca/2026-06-23/listing_master.csv")

In [58]:
mallorca_enrich_col = mallorca_enrich.columns.tolist()

In [59]:
len(mallorca_enrich_col)

100

In [60]:
mallorca_raw_col = mallorca_raw.columns.tolist()

In [61]:
len(mallorca_raw_col)

90

In [62]:
add_columns = list(set(mallorca_enrich_col) - set(mallorca_raw_col))

In [63]:
add_columns

['price_per_bedroom',
 'total_days',
 'host_tenure_years',
 'neighbourhood_listing_count',
 'estimated_revenue',
 'neighbourhood_average_rating',
 'neighbourhood_median_price',
 'occupied_days',
 'review_frequency',
 'occupancy_rate']

In [37]:
mallorca_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 14817 entries, 0 to 14816
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            14817 non-null  int64
 1   listing_url                                   14817 non-null  str
 2   scrape_id                                     14817 non-null  int64
 3   last_scraped                                  14817 non-null  str
 4   source                                        14817 non-null  str
 5   name                                          14817 non-null  str
 6   description                                   14529 non-null  str
 7   neighborhood_overview                         14817 non-null  float64
 8   picture_url                                   14817 non-null  str
 9   host_id                                       14817 non-null  int64
 10  host_url                                      14817 non-null  str
 11  host_profile_id                               14817 non-null  int64
 12  host_profile_url                              14815 non-null  str
 13  host_name                                     14817 non-null  str
 14  host_since                                    14817 non-null  float64
 15  hosts_time_as_user_years                      14817 non-null  int64
 16  hosts_time_as_user_months                     14817 non-null  int64
 17  hosts_time_as_host_years                      14817 non-null  int64
 18  hosts_time_as_host_months                     14817 non-null  int64
 19  host_location                                 10902 non-null  str
 20  host_about                                    10422 non-null  str
 21  host_response_time                            14817 non-null  float64
 22  host_response_rate                            14817 non-null  float64
 23  host_acceptance_rate                          14817 non-null  float64
 24  host_is_superhost                             14817 non-null  str
 25  host_thumbnail_url                            14817 non-null  float64
 26  host_picture_url                              14817 non-null  str
 27  host_neighbourhood                            14817 non-null  float64
 28  host_listings_count                           14817 non-null  int64
 29  host_total_listings_count                     14817 non-null  float64
 30  host_verifications                            14817 non-null  float64
 31  host_has_profile_pic                          14817 non-null  str
 32  host_identity_verified                        14817 non-null  str
 33  neighbourhood                                 14817 non-null  float64
 34  neighbourhood_cleansed                        14817 non-null  str
 35  neighbourhood_group_cleansed                  14817 non-null  float64
 36  latitude                                      14817 non-null  float64
 37  longitude                                     14817 non-null  float64
 38  property_type                                 14817 non-null  str
 39  room_type                                     14817 non-null  str
 40  accommodates                                  14817 non-null  str
 41  bathrooms                                     14817 non-null  float64
 42  bathrooms_text                                14812 non-null  str
 43  bedrooms                                      14817 non-null  float64
 44  beds                                          14817 non-null  float64
 45  amenities                                     14817 non-null  str
 46  price                                         14817 non-null  float64
 47  price_quote_checkin_date                      14367 non-null  str
 48  price_quote_checkout_date                     14367 non-null  str
 49  price_quote_total_price                       14817 non-null  float64
 50  price_quote_price_per_night                   14817 non-null  float64
 51  price_quote_raw                               14367 non-null  str
 52  minimum_nights                                14817 non-null  float64
 53  maximum_nights                                14817 non-null  float64
 54  minimum_minimum_nights                        14817 non-null  float64
 55  maximum_minimum_nights                        14817 non-null  float64
 56  minimum_maximum_nights                        14817 non-null  float64
 57  maximum_maximum_nights                        14817 non-null  float64
 58  minimum_nights_avg_ntm                        14817 non-null  float64
 59  maximum_nights_avg_ntm                        14817 non-null  float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              14806 non-null  str
 62  availability_30                               14817 non-null  int64
 63  availability_60                               14817 non-null  int64
 64  availability_90                               14817 non-null  int64
 65  availability_365                              14817 non-null  int64
 66  calendar_last_scraped                         14817 non-null  str
 67  number_of_reviews                             14817 non-null  int64
 68  number_of_reviews_ltm                         14817 non-null  int64
 69  number_of_reviews_l30d                        14817 non-null  int64
 70  availability_eoy                              14817 non-null  int64
 71  number_of_reviews_ly                          14817 non-null  int64
 72  estimated_occupancy_l365d                     14817 non-null  int64
 73  estimated_revenue_l365d                       14817 non-null  float64
 74  first_review                                  11609 non-null  str
 75  last_review                                   11609 non-null  str
 76  review_scores_rating                          14817 non-null  float64
 77  review_scores_accuracy                        14817 non-null  float64
 78  review_scores_cleanliness                     14817 non-null  float64
 79  review_scores_checkin                         14817 non-null  float64
 80  review_scores_communication                   14817 non-null  float64
 81  review_scores_location                        14817 non-null  float64
 82  review_scores_value                           14817 non-null  float64
 83  license                                       14754 non-null  str
 84  instant_bookable                              14817 non-null  float64
 85  calculated_host_listings_count                14817 non-null  int64
 86  calculated_host_listings_count_entire_homes   14817 non-null  int64
 87  calculated_host_listings_count_private_rooms  14817 non-null  int64
 88  calculated_host_listings_count_shared_rooms   14817 non-null  int64
 89  reviews_per_month                             14817 non-null  float64
dtypes: float64(38), int64(23), str(29)
memory usage: 10.2 MB

In [69]:
mallorca_enrich['host_since']

0        1970-01-01
1        1970-01-01
2        1970-01-01
3        1970-01-01
4        1970-01-01
            ...
14812    1970-01-01
14813    1970-01-01
14814    1970-01-01
14815    1970-01-01
14816    1970-01-01
Name: host_since, Length: 14817, dtype: str